/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.layered01.view;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kasun
 */
public class LayoutView extends javax.swing.JFrame {

    /**
     * Creates new form LayoutView
     */
    public LayoutView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        headerPanel = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        sidePanel = new keeptoo.KGradientPanel();
        jSeparator1 = new javax.swing.JSeparator();
        itemManageButton = new javax.swing.JButton();
        manageCustButton = new javax.swing.JButton();
        manageOrderButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        bodyPanel = new keeptoo.KGradientPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setkEndColor(new java.awt.Color(43, 157, 168));
        headerPanel.setkGradientFocus(700);
        headerPanel.setkStartColor(new java.awt.Color(177, 145, 214));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/systemimage/icons8-supermarket-94.png"))); // NOI18N
        jLabel1.setText("Supermarket");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1249, Short.MAX_VALUE)
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidePanel.setkEndColor(new java.awt.Color(94, 178, 162));
        sidePanel.setkGradientFocus(600);
        sidePanel.setkStartColor(new java.awt.Color(170, 124, 222));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        itemManageButton.setBackground(new java.awt.Color(170, 124, 230));
        itemManageButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        itemManageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/systemimage/icons8-new-item-48.png"))); // NOI18N
        itemManageButton.setText("Manage Item");
        itemManageButton.setBorder(null);
        itemManageButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemManageButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        itemManageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemManageButtonActionPerformed(evt);
            }
        });

        manageCustButton.setBackground(new java.awt.Color(170, 124, 222));
        manageCustButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        manageCustButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/systemimage/username1.png"))); // NOI18N
        manageCustButton.setText("Manage Customer");
        manageCustButton.setBorder(null);
        manageCustButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageCustButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        manageCustButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustButtonActionPerformed(evt);
            }
        });

        manageOrderButton.setBackground(new java.awt.Color(170, 124, 230));
        manageOrderButton.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        manageOrderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/systemimage/icons8-purchase-order-48.png"))); // NOI18N
        manageOrderButton.setText("Manage Order ");
        manageOrderButton.setBorder(null);
        manageOrderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageOrderButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        manageOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrderButtonActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(itemManageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageOrderButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(manageCustButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageCustButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemManageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 485, Short.MAX_VALUE))
        );

        bodyPanel.setkEndColor(new java.awt.Color(179, 217, 198));
        bodyPanel.setkStartColor(new java.awt.Color(215, 219, 232));
        bodyPanel.setkTransparentControls(false);

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemManageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemManageButtonActionPerformed
        loadItemManage();
    }//GEN-LAST:event_itemManageButtonActionPerformed

    private void manageCustButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustButtonActionPerformed
        loaddCustomerManagePanel();
    }//GEN-LAST:event_manageCustButtonActionPerformed

    private void manageOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrderButtonActionPerformed
        loaddManageOrderPanel();
    }//GEN-LAST:event_manageOrderButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LayoutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LayoutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LayoutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LayoutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LayoutView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KGradientPanel bodyPanel;
    private keeptoo.KGradientPanel headerPanel;
    private javax.swing.JButton itemManageButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton manageCustButton;
    private javax.swing.JButton manageOrderButton;
    private keeptoo.KGradientPanel sidePanel;
    // End of variables declaration//GEN-END:variables

    private void loaddCustomerManagePanel() {
        try {
            bodyPanel.removeAll();
            CustomerPnelView customerPnelView = new CustomerPnelView();
            customerPnelView.setSize(bodyPanel.getWidth(), bodyPanel.getHeight());
            bodyPanel.add(customerPnelView);
            bodyPanel.repaint();
            bodyPanel.revalidate();
        } catch (Exception ex) {
            Logger.getLogger(LayoutView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadItemManage() {
        bodyPanel.removeAll();
        ItemPanelView itemPanelView = new ItemPanelView();
        itemPanelView.setSize(bodyPanel.getWidth(), bodyPanel.getHeight());
        bodyPanel.add(itemPanelView);
        bodyPanel.repaint();
        bodyPanel.revalidate();

    }

    private void loaddManageOrderPanel() {
        bodyPanel.removeAll();
        OrderViewManagePanel orderViewManagePanel = new OrderViewManagePanel();
        orderViewManagePanel.setSize(bodyPanel.getWidth(), bodyPanel.getHeight());
        bodyPanel.add(orderViewManagePanel);
        bodyPanel.repaint();
        bodyPanel.revalidate();
    }
}
