/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos.layered01.view;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pos.layered01.controller.CustomerController;
import pos.layered01.controller.ItemController;
import pos.layered01.controller.OrderController;
import pos.layered01.dto.CustomerDTO;
import pos.layered01.dto.ItemDTO;
import pos.layered01.dto.OrderDTO;
import pos.layered01.dto.OrderDetailDTO;

/**
 *
 * @author kasun
 */
public class OrderViewManagePanel extends javax.swing.JPanel {
    private List<OrderDetailDTO> orderDetailDTOs = new ArrayList<>();
    CustomerController customerController;
    ItemController itemController;
    OrderController orderController;

    /**
     * Creates new form OrderViewManagePanel
     */
    public OrderViewManagePanel() {
        customerController = new CustomerController();
        itemController = new ItemController();
        orderController = new OrderController();
        initComponents();
        laddTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel4 = new keeptoo.KGradientPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        orderId_Text = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        customerId_Text = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        itemCod_Text = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        qty_Text = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        discount_Text = new javax.swing.JTextField();
        placeOrderButton = new javax.swing.JButton();
        addItemBttn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        searchCust = new javax.swing.JButton();
        searchCustIdLebel = new javax.swing.JLabel();
        searchItem = new javax.swing.JButton();
        searchItemCode = new javax.swing.JLabel();

        kGradientPanel4.setkEndColor(new java.awt.Color(62, 102, 123));
        kGradientPanel4.setkGradientFocus(700);
        kGradientPanel4.setkStartColor(new java.awt.Color(210, 155, 233));
        kGradientPanel4.setkTransparentControls(false);

        jLabel13.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel13.setText("Order");

        jLabel14.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel14.setText("Order ID");

        jLabel15.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel15.setText("Customer ID");

        jLabel16.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel16.setText("Item Code");

        jLabel17.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel17.setText("Qty");

        jLabel18.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel18.setText("Discount");

        placeOrderButton.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        placeOrderButton.setText("Place Order");
        placeOrderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        placeOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderButtonupdateButtonActionPerformed(evt);
            }
        });

        addItemBttn.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        addItemBttn.setText("Add Item");
        addItemBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addItemBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemBttndeleteButtonActionPerformed(evt);
            }
        });

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        orderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderTableitemTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(orderTable);

        searchCust.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        searchCust.setText("Search ");
        searchCust.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustdeleteButtonActionPerformed(evt);
            }
        });

        searchItem.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        searchItem.setText("Search ");
        searchItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemdeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel4Layout.createSequentialGroup()
                        .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(orderId_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel4Layout.createSequentialGroup()
                                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(kGradientPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(discount_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                                    .addGroup(kGradientPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(qty_Text))
                                    .addGroup(kGradientPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(itemCod_Text))
                                    .addGroup(kGradientPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(customerId_Text)))
                                .addGap(18, 18, 18)
                                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel4Layout.createSequentialGroup()
                                        .addComponent(searchCust)
                                        .addGap(18, 18, 18)
                                        .addComponent(searchCustIdLebel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(kGradientPanel4Layout.createSequentialGroup()
                                        .addComponent(searchItem)
                                        .addGap(18, 18, 18)
                                        .addComponent(searchItemCode, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                                    .addGroup(kGradientPanel4Layout.createSequentialGroup()
                                        .addComponent(addItemBttn)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(placeOrderButton)))
                .addContainerGap())
            .addComponent(jScrollPane3)
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderId_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel4Layout.createSequentialGroup()
                        .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerId_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchCust)
                            .addComponent(searchCustIdLebel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemCod_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchItem)
                        .addComponent(searchItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qty_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discount_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addItemBttn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(placeOrderButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void placeOrderButtonupdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderButtonupdateButtonActionPerformed
        placeOrder();
    }//GEN-LAST:event_placeOrderButtonupdateButtonActionPerformed

    private void addItemBttndeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemBttndeleteButtonActionPerformed
        addToTable();
    }//GEN-LAST:event_addItemBttndeleteButtonActionPerformed

    private void orderTableitemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderTableitemTableMouseClicked
        //searchItem();
    }//GEN-LAST:event_orderTableitemTableMouseClicked

    private void searchCustdeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustdeleteButtonActionPerformed
        searchCustomer();
    }//GEN-LAST:event_searchCustdeleteButtonActionPerformed

    private void searchItemdeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemdeleteButtonActionPerformed
        searchItem();
    }//GEN-LAST:event_searchItemdeleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemBttn;
    private javax.swing.JTextField customerId_Text;
    private javax.swing.JTextField discount_Text;
    private javax.swing.JTextField itemCod_Text;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private javax.swing.JTextField orderId_Text;
    private javax.swing.JTable orderTable;
    private javax.swing.JButton placeOrderButton;
    private javax.swing.JTextField qty_Text;
    private javax.swing.JButton searchCust;
    private javax.swing.JLabel searchCustIdLebel;
    private javax.swing.JButton searchItem;
    private javax.swing.JLabel searchItemCode;
    // End of variables declaration//GEN-END:variables

    private void laddTable() {
        String[] column = {"Item Code", "Qty", "Discount"};
        DefaultTableModel dtm = new DefaultTableModel(column, 0) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        orderTable.setModel(dtm);
    }

    private void cleanItemData() {
        itemCod_Text.setText("");
        qty_Text.setText("");
        discount_Text.setText("");
        searchItemCode.setText("");
    }

    private void searchCustomer() {
        try {
            String custId = customerId_Text.getText();
            CustomerDTO customerDTO = customerController.getCustomer(custId);
            if (customerDTO != null) {
                searchCustIdLebel.setText(customerDTO.getName() + ", " + customerDTO.getAddress());

            } else {
                JOptionPane.showMessageDialog(this, "Customer Not Found");
            }
        } catch (Exception ex) {
            Logger.getLogger(OrderViewManagePanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void searchItem() {
        try {
            String itemCode = itemCod_Text.getText();
            ItemDTO itemDTO = itemController.getITem(itemCode);
            if (itemDTO != null) {
                searchItemCode.setText(itemDTO.getDescription() + ", " + itemDTO.getUnitprice() + ", " + itemDTO.getQtyOnHand());

            } else {
                JOptionPane.showMessageDialog(this, "Item Not Found");
            }
        } catch (Exception ex) {
            Logger.getLogger(OrderViewManagePanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void addToTable() {
        OrderDetailDTO odm = new OrderDetailDTO(itemCod_Text.getText(),
                Integer.parseInt(qty_Text.getText()),
                Double.parseDouble(discount_Text.getText()));
        orderDetailDTOs.add(odm);

        Object[] rawData = {odm.getItemCode(), odm.getOrderQty(), odm.getDiscount()};
        DefaultTableModel dtm = (DefaultTableModel) orderTable.getModel();
        dtm.addRow(rawData);
        cleanItemData();
    }

    private void placeOrder() {
        try {
            OrderDTO orderDTO = new OrderDTO(orderId_Text.getText(), customerId_Text.getText(), orderDetailDTOs);
            String result = orderController.placeOrder(orderDTO);
            JOptionPane.showMessageDialog(this, result);
        } catch (Exception ex) {
            Logger.getLogger(OrderViewManagePanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        clearForm();
    }
    
     private void clearForm() {
        laddTable();
        orderId_Text.setText("");
        customerId_Text.setText("");
        searchCustIdLebel.setText("");
    }
}
